export { default as HomeView } from '@/views/HomeView.vue'
export { default as LoginView } from '@/views/LoginView.vue'
export { default as SignUpView } from '@/views/SignUpView.vue'
export { default as TangramListView } from '@/views/TangramListView.vue'
export { default as TangramDetailView } from '@/views/TangramDetailView.vue'
export { default as ErrorView } from '@/views/ErrorView.vue'
export { default as NotFoundView } from '@/views/NotFoundView.vue'
export { default as ContactView } from '@/views/ContactView.vue'
